 //------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliquationGestionDepenses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.ModelBinding;

    public partial class TDepenses
    {
        public int IdDepense { get; set; }
        public System.DateTime dateDepesse { get; set; }
        [Required(ErrorMessage = "Valeur non valide")]
        public double prixDepense { get; set; }
        [Required(ErrorMessage = "Veuillez saisir un nom")]
        public string nomDepense { get; set; }
    }
}
