//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliquationGestionDepenses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDepenses
    {
        public int IdDepense { get; set; }
        public System.DateTime dateDepesse { get; set; }
        public double prixDepense { get; set; }
        public string nomDepense { get; set; }
        public string typeDepense { get; set; }
    }
}
